baseurl = "https://sunsea.ru"
languageCode = "ru"
title = "ManTrer Govorun"
theme = "kiss"
copyright = "&copy; <a href=\"https://github.com/mantrer\">Mantrer Govorun</a> 2020"
#disqusShortname = "shortname"
googleAnalytics = ""
Paginate = 5 # Number of posts per page
enableRobotsTXT = true

[params.rss] # Adding this tag enables RSS feed
includeContent = false # Includes whole content in rss
authorName = "Mantrer Govorun" # Author full name
authorEmail = "mantrer@gmail.com" # Author email

[params.assets]
customCSS = ["css/custom.css"]

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "" # Title for home page
poweredby = false # Adds powered by hugo and kiss below Copyright
related = true # Includes related articles at the bottom of the article
codeCopy = true # Add copy button above code blocks
taxonomiesCount = true # Add taxonomies count

[params.features]
disqusOnDemand = true  # Load Disqus comments on click


[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]
twitter = ""
github = ""
email = "mantrer@gmail.com"
linkedin = ""
facebook = ""
instagram = ""
codepen = ""
rss = "index.xml" # Add this to show RSS button in social.

[params.social.config]
platforms = ["github","facebook","twitter","instagram","email","codepen","linkedin"]

[params.matomoAnalytics]
siteID = 1
rootURL = ""

[params.fathomAnalytics]
rootURL = ""

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true
